Search.appendIndex(
    [
                {
            "fqsen": "\\app\\controllers\\MaterialController",
            "name": "MaterialController",
            "summary": "",
            "url": "classes/app-controllers-MaterialController.html"
        },                {
            "fqsen": "\\app\\controllers\\MaterialController\u003A\u003AactionExposition\u0028\u0029",
            "name": "actionExposition",
            "summary": "",
            "url": "classes/app-controllers-MaterialController.html#method_actionExposition"
        },                {
            "fqsen": "\\app\\controllers\\MaterialController\u003A\u003AactionGallery\u0028\u0029",
            "name": "actionGallery",
            "summary": "",
            "url": "classes/app-controllers-MaterialController.html#method_actionGallery"
        },                {
            "fqsen": "\\app\\controllers\\MaterialController\u003A\u003AactionAdditem\u0028\u0029",
            "name": "actionAdditem",
            "summary": "",
            "url": "classes/app-controllers-MaterialController.html#method_actionAdditem"
        },                {
            "fqsen": "\\app\\controllers\\MaterialController\u003A\u003AactionAdditemPost\u0028\u0029",
            "name": "actionAdditemPost",
            "summary": "",
            "url": "classes/app-controllers-MaterialController.html#method_actionAdditemPost"
        },                {
            "fqsen": "\\app\\controllers\\MaterialController\u003A\u003AactionView\u0028\u0029",
            "name": "actionView",
            "summary": "",
            "url": "classes/app-controllers-MaterialController.html#method_actionView"
        },                {
            "fqsen": "\\app\\controllers\\MaterialController\u003A\u003AactionSearch\u0028\u0029",
            "name": "actionSearch",
            "summary": "",
            "url": "classes/app-controllers-MaterialController.html#method_actionSearch"
        },                {
            "fqsen": "\\app\\controllers\\MaterialController\u003A\u003AactionDelete\u0028\u0029",
            "name": "actionDelete",
            "summary": "",
            "url": "classes/app-controllers-MaterialController.html#method_actionDelete"
        },                {
            "fqsen": "\\app\\controllers\\MaterialController\u003A\u003A\u0024layout",
            "name": "layout",
            "summary": "",
            "url": "classes/app-controllers-MaterialController.html#property_layout"
        },                {
            "fqsen": "\\app\\controllers\\SiteController",
            "name": "SiteController",
            "summary": "",
            "url": "classes/app-controllers-SiteController.html"
        },                {
            "fqsen": "\\app\\controllers\\SiteController\u003A\u003Abehaviors\u0028\u0029",
            "name": "behaviors",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/app-controllers-SiteController.html#method_behaviors"
        },                {
            "fqsen": "\\app\\controllers\\SiteController\u003A\u003Aactions\u0028\u0029",
            "name": "actions",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/app-controllers-SiteController.html#method_actions"
        },                {
            "fqsen": "\\app\\controllers\\SiteController\u003A\u003AactionIndex\u0028\u0029",
            "name": "actionIndex",
            "summary": "Displays\u0020homepage.",
            "url": "classes/app-controllers-SiteController.html#method_actionIndex"
        },                {
            "fqsen": "\\app\\controllers\\SiteController\u003A\u003AactionLogin\u0028\u0029",
            "name": "actionLogin",
            "summary": "Login\u0020action.",
            "url": "classes/app-controllers-SiteController.html#method_actionLogin"
        },                {
            "fqsen": "\\app\\controllers\\SiteController\u003A\u003AactionLogout\u0028\u0029",
            "name": "actionLogout",
            "summary": "Logout\u0020action.",
            "url": "classes/app-controllers-SiteController.html#method_actionLogout"
        },                {
            "fqsen": "\\app\\controllers\\SiteController\u003A\u003AactionContact\u0028\u0029",
            "name": "actionContact",
            "summary": "Displays\u0020contact\u0020page.",
            "url": "classes/app-controllers-SiteController.html#method_actionContact"
        },                {
            "fqsen": "\\app\\controllers\\SiteController\u003A\u003AactionAbout\u0028\u0029",
            "name": "actionAbout",
            "summary": "Displays\u0020about\u0020page.",
            "url": "classes/app-controllers-SiteController.html#method_actionAbout"
        },                {
            "fqsen": "\\app\\controllers\\UserController",
            "name": "UserController",
            "summary": "",
            "url": "classes/app-controllers-UserController.html"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionJoin\u0028\u0029",
            "name": "actionJoin",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionJoin"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionJoinPost\u0028\u0029",
            "name": "actionJoinPost",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionJoinPost"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionLogin\u0028\u0029",
            "name": "actionLogin",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionLogin"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionLoginPost\u0028\u0029",
            "name": "actionLoginPost",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionLoginPost"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionLogout\u0028\u0029",
            "name": "actionLogout",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionLogout"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AredirectToRestriced\u0028\u0029",
            "name": "redirectToRestriced",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_redirectToRestriced"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionSetpassword\u0028\u0029",
            "name": "actionSetpassword",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionSetpassword"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionSetpasswordPost\u0028\u0029",
            "name": "actionSetpasswordPost",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionSetpasswordPost"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionSetemail\u0028\u0029",
            "name": "actionSetemail",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionSetemail"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionSetemailPost\u0028\u0029",
            "name": "actionSetemailPost",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionSetemailPost"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionForget\u0028\u0029",
            "name": "actionForget",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionForget"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionForgetPost\u0028\u0029",
            "name": "actionForgetPost",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionForgetPost"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionLk\u0028\u0029",
            "name": "actionLk",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionLk"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003AactionRestricted\u0028\u0029",
            "name": "actionRestricted",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#method_actionRestricted"
        },                {
            "fqsen": "\\app\\controllers\\UserController\u003A\u003A\u0024layout",
            "name": "layout",
            "summary": "",
            "url": "classes/app-controllers-UserController.html#property_layout"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\app\\controllers",
            "name": "controllers",
            "summary": "",
            "url": "namespaces/app-controllers.html"
        },                {
            "fqsen": "\\app",
            "name": "app",
            "summary": "",
            "url": "namespaces/app.html"
        }            ]
);
